### ISSUE TITLE
endpoint.method is undefined

### ISSUE THREAD

**Issue by Laazarus** [GuidionDev/inversify-express-doc#7] opened 2018-06-21 07:43 UTC
Hello,

looks like inversify-express-doc is not able to find the endpoint. 
When I try to access the documentation from the /doc endpoint I get an exception because endpoint.method is undefined.
i went in the apidoc.pug and removed the function toUpperCase() in order to display the page and looks like the library cannot retrieve the paths from my controller.

I followed the documentation and I cannot see what i am doing wronng?

**Comment by Rawne** [comment] 2019-04-08 07:42
Hi @Laazarus , sorry for the late reply, that does indeed probably mean that inversify-express-doc failed to load any controller info. Did you start the express server before loading the documentation info? Ill update the documentation to reflect this.

Since the issue is so old, i'll close it for now, but feel free to re-open or comment.

**Closed as completed by Rawne** 2019-04-08 07:42 UTC
